version: '3'

services:
  todosDB:
    image: 'postgres:15.3'
    container_name: 'todos-db'
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sistemas87
    volumes:
      - './postgres:/var/lib/postgresql/data'
